# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-10 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_auto_20161115_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumlist',
            name='albums',
            field=models.ManyToManyField(through='albums.AlbumSelection', to='albums.Album'),
        ),
    ]
