# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_albumlist_albums'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albumselection',
            options={'ordering': ['album_list', 'position']},
        ),
    ]
