# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-11-23 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0011_auto_20190504_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
        migrations.AlterField(
            model_name='album',
            name='sample',
            field=models.FileField(blank=True, null=True, upload_to='samples'),
        ),
    ]
