# Generated by Django 3.2.14 on 2022-08-05 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0012_auto_20201123_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-year', 'artist']},
        ),
    ]
