
(function(jQuery){jQuery.fn.__bind__=jQuery.fn.bind;jQuery.fn.__unbind__=jQuery.fn.unbind;jQuery.fn.__find__=jQuery.fn.find;var hotkeys={version:'0.7.9',override:/keypress|keydown|keyup/g,triggersMap:{},specialKeys:{27:'esc',9:'tab',32:'space',13:'return',8:'backspace',145:'scroll',20:'capslock',144:'numlock',19:'pause',45:'insert',36:'home',46:'del',35:'end',33:'pageup',34:'pagedown',37:'left',38:'up',39:'right',40:'down',109:'-',112:'f1',113:'f2',114:'f3',115:'f4',116:'f5',117:'f6',118:'f7',119:'f8',120:'f9',121:'f10',122:'f11',123:'f12',191:'/'},shiftNums:{"`":"~","1":"!","2":"@","3":"#","4":"$","5":"%","6":"^","7":"&","8":"*","9":"(","0":")","-":"_","=":"+",";":":","'":"\"",",":"<",".":">","/":"?","\\":"|"},newTrigger:function(type,combi,callback){var result={};result[type]={};result[type][combi]={cb:callback,disableInInput:false};return result;}};hotkeys.specialKeys=jQuery.extend(hotkeys.specialKeys,{96:'0',97:'1',98:'2',99:'3',100:'4',101:'5',102:'6',103:'7',104:'8',105:'9',106:'*',107:'+',109:'-',110:'.',111:'/'});jQuery.fn.find=function(selector){this.query=selector;return jQuery.fn.__find__.apply(this,arguments);};jQuery.fn.unbind=function(type,combi,fn){if(jQuery.isFunction(combi)){fn=combi;combi=null;}
if(combi&&typeof combi==='string'){var selectorId=((this.prevObject&&this.prevObject.query)||(this[0].id&&this[0].id)||this[0]).toString();var hkTypes=type.split(' ');for(var x=0;x<hkTypes.length;x++){delete hotkeys.triggersMap[selectorId][hkTypes[x]][combi];}}
return this.__unbind__(type,fn);};jQuery.fn.bind=function(type,data,fn){var handle=type.match(hotkeys.override);if(jQuery.isFunction(data)||!handle){return this.__bind__(type,data,fn);}
else{var result=null,pass2jq=jQuery.trim(type.replace(hotkeys.override,''));if(pass2jq){result=this.__bind__(pass2jq,data,fn);}
if(typeof data==="string"){data={'combi':data};}
if(data.combi){for(var x=0;x<handle.length;x++){var eventType=handle[x];var combi=data.combi.toLowerCase(),trigger=hotkeys.newTrigger(eventType,combi,fn),selectorId=((this.prevObject&&this.prevObject.query)||(this[0].id&&this[0].id)||this[0]).toString();trigger[eventType][combi].disableInInput=data.disableInInput;if(!hotkeys.triggersMap[selectorId]){hotkeys.triggersMap[selectorId]=trigger;}
else if(!hotkeys.triggersMap[selectorId][eventType]){hotkeys.triggersMap[selectorId][eventType]=trigger[eventType];}
var mapPoint=hotkeys.triggersMap[selectorId][eventType][combi];if(!mapPoint){hotkeys.triggersMap[selectorId][eventType][combi]=[trigger[eventType][combi]];}
else if(mapPoint.constructor!==Array){hotkeys.triggersMap[selectorId][eventType][combi]=[mapPoint];}
else{hotkeys.triggersMap[selectorId][eventType][combi][mapPoint.length]=trigger[eventType][combi];}
this.each(function(){var jqElem=jQuery(this);if(jqElem.attr('hkId')&&jqElem.attr('hkId')!==selectorId){selectorId=jqElem.attr('hkId')+";"+selectorId;}
jqElem.attr('hkId',selectorId);});result=this.__bind__(handle.join(' '),data,hotkeys.handler)}}
return result;}};hotkeys.findElement=function(elem){if(!jQuery(elem).attr('hkId')){if(jQuery.browser.opera||jQuery.browser.safari){while(!jQuery(elem).attr('hkId')&&elem.parentNode){elem=elem.parentNode;}}}
return elem;};hotkeys.handler=function(event){var target=hotkeys.findElement(event.currentTarget),jTarget=jQuery(target),ids=jTarget.attr('hkId');if(ids){ids=ids.split(';');var code=event.which,type=event.type,special=hotkeys.specialKeys[code],character=!special&&String.fromCharCode(code).toLowerCase(),shift=event.shiftKey,ctrl=event.ctrlKey,alt=event.altKey||event.originalEvent.altKey,mapPoint=null;for(var x=0;x<ids.length;x++){if(hotkeys.triggersMap[ids[x]][type]){mapPoint=hotkeys.triggersMap[ids[x]][type];break;}}
if(mapPoint){var trigger;if(!shift&&!ctrl&&!alt){trigger=mapPoint[special]||(character&&mapPoint[character]);}
else{var modif='';if(alt)modif+='alt+';if(ctrl)modif+='ctrl+';if(shift)modif+='shift+';trigger=mapPoint[modif+special];if(!trigger){if(character){trigger=mapPoint[modif+character]||mapPoint[modif+hotkeys.shiftNums[character]]||(modif==='shift+'&&mapPoint[hotkeys.shiftNums[character]]);}}}
if(trigger){var result=false;for(var x=0;x<trigger.length;x++){if(trigger[x].disableInInput){var elem=jQuery(event.target);if(jTarget.is("input")||jTarget.is("textarea")||jTarget.is("select")||elem.is("input")||elem.is("textarea")||elem.is("select")){return true;}}
result=result||trigger[x].cb.apply(this,[event]);}
return result;}}}};window.hotkeys=hotkeys;return jQuery;})(jQuery); 
var ap_instances=new Array();function ap_stopAll(playerID){for(var i=0;i<ap_instances.length;i++){try{if(ap_instances[i]!=playerID)document.getElementById("audioplayer"+ap_instances[i].toString()).SetVariable("closePlayer",1);else document.getElementById("audioplayer"+ap_instances[i].toString()).SetVariable("closePlayer",0);}catch(errorObject){}}}
function ap_registerPlayers(){var objectID;var objectTags=document.getElementsByTagName("object");for(var i=0;i<objectTags.length;i++){objectID=objectTags[i].id;if(objectID.indexOf("audioplayer")==0){ap_instances[i]=objectID.substring(11,objectID.length);}}}
var ap_clearID=setInterval(ap_registerPlayers,100); 
(function(){var keys,newWindow,photoLoader,programNotes,stylesheets,thumbnails,web,webNext,webPreload,webPrev;stylesheets=function(){if(jQuery.browser.safari){$('head').append("<link type='text/css' rel='stylesheet' href='/style/safari.css'>");}
if(jQuery.browser.chrome){$('head').append("<link type='text/css' rel='stylesheet' href='/style/chrome.css'>");}
if(jQuery.browser.opera){return $('head').append("<link type='text/css' rel='stylesheet' href='/style/opera.css'>");}};newWindow=function(){return $('a.new-window').live('click',function(){window.open(this.href);return false;});};programNotes=function(){$('.programNotesOpen').click(function(){$(this).prevAll('.programNotes').slideDown('medium');$(this).html('').animate({marginBottom:"0px"},'medium');return false;});return $('.programNotesClose').click(function(){$(this).parent().slideUp('medium');$(this).parent().nextAll('.programNotesOpen').html('[+]&nbsp;Program Notes').animate({marginBottom:"30px"},'medium');return false;});};thumbnails=function(){var offOp;offOp=0.4;return $('#galleryThumbs').find('img:not(img.on)').mouseover(function(){return $(this).animate({opacity:1},200);}).mouseout(function(){return $(this).animate({opacity:offOp},200);});};photoLoader=function(){var height,id,section,siteSection,srcString,title,width;if($('#photoLoaderInfo').length!==0){siteSection=$('#photoLoaderSiteSection').html();section=$('#photoLoaderSection').html();id=$('#photoLoaderID').html();width=$('#photoLoaderWidth').html();height=$('#photoLoaderHeight').html();title=$('#photoLoaderTitle').html();if(siteSection==='photography'){srcString='/media/'+siteSection+'/'+section+'/'+id+'.jpg';}else{srcString='/media/'+siteSection+'/'+id+'.jpg';}
return $(function(){var img;img=new Image();return $(img).load(function(){$(this).hide();$('#pictureDiv').removeClass('loading').append(this);return $(this).fadeIn();}).attr('src',srcString).attr('width',width).attr('height',height).attr('alt',title);});}};keys=function(){if(!($('#pageWeb').length>0)){if($('a#previous').length!==0){$(document).bind('keydown','left',function(){return window.location=$('a#previous').attr('href');});}
if($('a#next').length!==0){return $(document).bind('keydown','right',function(){return window.location=$('a#next').attr('href');});}}};web=function(){var animationTime,containerSize;if($('#pageWeb').length>0){containerSize=330;if($.browser.msie&&$.browser.version.substr(0,1)==='7'&&$('#piece').html()!==''){$('#pieceList ul').css('opacity',0.1);}
if($('#piece').html()!==''){webPreload("/media/web/"+($('#piece').text())+"/1.jpg",1);}
$('#pieceList a').click(function(){var url;url=$(this).attr('href');$('#pieceListContainer ul').stop().animate({opacity:0.1},animationTime);$('#pieceListContainer').stop().animate({width:100},animationTime);$('#webOverlay').animate({width:'100%'},animationTime);$('#webFade').stop().animate({width:20},animationTime+20,function(){return window.location=url;});return false;});animationTime=200;$('#webToggle').hover(function(){return $(this).find('.inner').removeClass('off').addClass('on');},function(){return $(this).find('.inner').removeClass('on').addClass('off');});$('#webToggle').click(function(){if($('#pieceListContainer').attr('class').match(/collapsed/)){$('#webOverlay').find('.inner').removeClass('expand').addClass('contract');$('#webOverlay').animate({width:20,right:20},animationTime);$('#pieceListContainer').stop().animate({width:containerSize},animationTime);$('#pieceListContainer ul').stop().animate({opacity:1},animationTime);$('#webFade').stop().animate({width:40},animationTime);$('#pieceListContainer').removeClass('collapsed');}else{$('#webFade').css('background','background: url(/images/webFade.png) 0 0 repeat-y;');$('#webOverlay').find('.inner').removeClass('contract').addClass('expand');$('#webOverlay').animate({width:'100%',right:0},animationTime);$('#pieceListContainer').stop().animate({width:100},animationTime);$('#pieceListContainer ul').stop().animate({opacity:0.1},animationTime);$('#webFade').stop().animate({width:20},animationTime);$('#pieceListContainer').addClass('collapsed');}
return false;});}
$('#next').live('click',function(){webNext();return false;});$('#previous').live('click',function(){webPrev();return false;});if($('a#next').length!==0){$(document).bind('keydown','right',function(){return webNext();});}
if($('a#previous').length!==0){return $(document).bind('keydown','left',function(){return webPrev();});}};webNext=function(){var images,next,number,url;number=parseInt($('#current').text(),10);images=parseInt($('#images').text(),10);next=number+1>images?1:number+1;url=$('#pieceContent img').attr('src').replace(/\d{1}.jpg/,""+next+".jpg");webPreload(url,next);return $('#current').html(next);};webPrev=function(){var images,next,number,url;number=parseInt($('#current').text(),10);images=parseInt($('#images').text(),10);next=number-1===0?images:number-1;url=$('#pieceContent img').attr('src').replace(/\d{1}.jpg/,""+next+".jpg");webPreload(url,next);return $('#current').html(next);};webPreload=function(url,number){var img;$('#webImage').html('').addClass('loading');img=new Image();return $(img).load(function(){$(this).hide();$('#webImage').removeClass('loading').append(this);return $(this).fadeIn();}).attr('src',url).attr('width',750).attr('alt',""+($('#name').html())+" Screenshot "+number);};$(function(){stylesheets();newWindow();programNotes();thumbnails();photoLoader();keys();return web();});}).call(this);
