# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-22 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('materials', models.CharField(max_length=400)),
                ('performers', models.CharField(blank=True, max_length=800)),
                ('duration', models.CharField(blank=True, max_length=10)),
                ('video', models.URLField(blank=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='composition')),
                ('description', models.TextField(blank=True)),
                ('score', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Graphic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('materials', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.FileField(upload_to='graphic')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='GraphicImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='graphic')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('graphic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Graphic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PhotoblogImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lightroom_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField()),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='photoblog/thubmnails')),
                ('image', models.FileField(blank=True, null=True, upload_to='photoblog/images')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PhotoblogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio', models.FileField(upload_to='recordings')),
                ('order', models.PositiveSmallIntegerField(blank=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RecordingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='web')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('tech', models.CharField(blank=True, max_length=400)),
                ('subtitle', models.CharField(blank=True, max_length=400)),
                ('link', models.URLField(blank=True)),
                ('source', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='web')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='WebImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='web')),
                ('video', models.URLField(blank=True)),
                ('web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Web')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='recording',
            name='recording_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.RecordingPage'),
        ),
        migrations.AddField(
            model_name='photoblogimage',
            name='tags',
            field=models.ManyToManyField(blank=True, to='portfolio.PhotoblogTag'),
        ),
    ]
