# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField()),
                ('materials', models.CharField(max_length=400)),
                ('performers', models.CharField(max_length=800)),
                ('video', models.URLField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='composition')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
    ]
