# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='slug',
            field=models.SlugField(default='hollow-earth', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='composition',
            name='performers',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='composition',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
