# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20160221_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='duration',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
