# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_composition_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composition',
            options={'ordering': ['-year']},
        ),
        migrations.AddField(
            model_name='composition',
            name='score',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
