# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20160312_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('tech', models.CharField(max_length=400)),
                ('subtitle', models.CharField(max_length=400)),
                ('link', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='WebItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, unique=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='web')),
                ('video', models.URLField(blank=True)),
                ('web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Web')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
