# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20160313_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webitem',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
