# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_web_source'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebItem',
            new_name='WebImage',
        ),
    ]
