# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20160326_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='web',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='web'),
        ),
    ]
