# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_web_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='web')),
            ],
        ),
    ]
