# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20160327_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio', models.FileField(upload_to='recordings')),
                ('order', models.PositiveSmallIntegerField(blank=True)),
                ('recording_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.RecordingPage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
