# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_auto_20160402_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic',
            name='image',
            field=models.FileField(default='asdf', upload_to='graphic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graphic',
            name='thumbnail',
            field=models.FileField(default='adsf', upload_to='graphic'),
            preserve_default=False,
        ),
    ]
