# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_auto_20160403_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graphicimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='graphicimage',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
