# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_auto_20160412_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic',
            name='materials',
            field=models.TextField(blank=True),
        ),
    ]
