# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_graphic_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic',
            name='materials',
            field=models.TextField(),
        ),
    ]
