# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-11 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_photoblogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoblogimage',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
