# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-18 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_auto_20160911_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoblogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='photoblogimage',
            name='tags',
            field=models.ManyToManyField(to='portfolio.PhotoblogTag'),
        ),
    ]
