# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-18 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_auto_20160918_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photoblogtag',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='photoblogtag',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
