# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-18 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_auto_20160918_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoblogimage',
            name='tags',
            field=models.ManyToManyField(blank=True, to='portfolio.PhotoblogTag'),
        ),
    ]
