# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-18 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_auto_20160918_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoblogimage',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='photoblogtag',
            options={'ordering': ['name']},
        ),
    ]
