# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-27 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20160922_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoblogimage',
            name='image',
        ),
        migrations.AddField(
            model_name='photoblogimage',
            name='image2000',
            field=models.FileField(blank=True, null=True, upload_to='photoblog/images2000'),
        ),
        migrations.AddField(
            model_name='photoblogimage',
            name='image700',
            field=models.FileField(blank=True, null=True, upload_to='photoblog/images700'),
        ),
    ]
