# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-20 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20161027_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='web')),
                ('order', models.PositiveSmallIntegerField(blank=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
