# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-20 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_homeproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeproject',
            name='order',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
