# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-20 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20161120_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeproject',
            name='slug',
            field=models.SlugField(default='foo', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
