# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-30 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20161120_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeproject',
            name='image_max_width',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
