# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-30 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_homeproject_image_max_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeproject',
            name='image_full_bleed',
            field=models.BooleanField(default=False),
        ),
    ]
