# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-30 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_homeproject_image_full_bleed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeproject',
            name='image_max_width',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
