# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-02 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20161130_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeproject',
            name='background',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
