# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-09 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_homeproject_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeproject',
            name='light_text',
            field=models.BooleanField(default=False),
        ),
    ]
