# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-23 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_homeproject_light_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeproject',
            name='image_full_bleed',
        ),
    ]
