# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-23 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_homeproject_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeproject',
            name='class_name',
        ),
    ]
