# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-23 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_remove_homeproject_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeproject',
            name='image_full_bleed',
            field=models.BooleanField(default=False),
        ),
    ]
