# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-07 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_remove_homeproject_image_full_bleed'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeproject',
            name='long_description',
            field=models.TextField(blank=True),
        ),
    ]
