# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-08 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_homeproject_long_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProjectMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('media', models.FileField(blank=True, null=True, upload_to='projects')),
                ('position', models.PositiveSmallIntegerField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.HomeProject')),
            ],
        ),
    ]
