# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-08 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_homeprojectmedia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeprojectmedia',
            old_name='media',
            new_name='image',
        ),
        migrations.AddField(
            model_name='homeprojectmedia',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='projects'),
        ),
    ]
