# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-09 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_homeprojectmedia_is_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeproject',
            name='code_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homeproject',
            name='visit_link',
            field=models.URLField(blank=True),
        ),
    ]
