# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_auto_20170209_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeprojectmedia',
            name='max_width',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
