# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_userprofile_headline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoblogimage',
            options={'ordering': ['-lightroom_id']},
        ),
        migrations.AlterField(
            model_name='photoblogimage',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='photoblog/thumbnails'),
        ),
    ]
