# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-11-23 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_auto_20190504_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProjectLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('order', models.IntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.HomeProject')),
            ],
        ),
    ]
