# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-11-24 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_homeprojectlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeproject',
            name='code_link',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='visit_link',
        ),
    ]
