# Generated by Django 3.2.14 on 2023-02-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_auto_20201124_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeproject',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
